set t_Co=256
call plug#begin('~/.config/nvim/autoload/plugged')
		Plug 'sheerun/vim-polyglot'
		Plug 'scrooloose/NERDTree'
		Plug 'sts10/vim-pink-moon'
		Plug 'vim-airline/vim-airline'
		Plug 'vim-airline/vim-airline-themes'
		Plug 'wadackel/vim-dogrun'
call plug#end()
